controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

velocity_controllers:
  ros__parameters:
    joints: 
      - joint_1
      - joint_2
      - joint_3
    command_interface: 
      - velocity
    state_interface:
      - position
      - velocity
      - effort